# Generated by Django 4.1 on 2023-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Имя категории', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Имя категории', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_body_en_us',
            field=models.TextField(default='No text', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_body_ru',
            field=models.TextField(default='No text', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Имя категории', max_length=255, unique=True),
        ),
    ]
