# Generated by Django 4.1 on 2023-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_body_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_body_ru',
        ),
        migrations.AlterField(
            model_name='post',
            name='text_body',
            field=models.TextField(default='No text ...'),
        ),
    ]
