# Generated by Django 4.1 on 2023-03-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_post_text_body_en_us_remove_post_text_body_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
    ]
