# Generated by Django 4.1 on 2023-03-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_name_en_us_category_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
    ]
