# Generated by Django 4.1 on 2023-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_post_text_body_en_us_remove_post_text_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_body',
            field=models.TextField(),
        ),
    ]
